---
- name: update cloudconfig
  hosts: coreos
  serial: 1
  gather_facts: no
  user: core

  roles:
    - role: etcd-certs-cfssl
    - role: extra-cas
    - role: cloud-config
    - role: safe_reboot

